volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: oyushakova/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    env_file: .env
    image: oyushakova/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: oyushakova/foodgram_gateway
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend